###############################################
# Large Mind Model (LMM) Configuration File
###############################################

# System settings
system:
  version: "0.1.0"
  log_level: "ERROR"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  storage_dir: "storage"
  cuda_enabled: true
  cuda_fallback: true  # Fall back to CPU if CUDA unavailable

# Development settings
development:
  rate: 0.001  # Age units per real second
  checkpoint_interval: 3600  # Seconds between state checkpoints (1 hour)
  critical_periods:
    enabled: true
    sensitivity_multiplier: 2.0

# Module settings
modules:
  # Memory module settings
  memory:
    working_memory_capacity: 7  # Items in working memory
    episodic_decay_rate: 0.05
    semantic_consolidation_threshold: 0.7
    vector_dimension: 768

  # Perception module settings
  perception:
    input_buffer_size: 10
    pattern_recognition_threshold: 0.6

  # Attention module settings
  attention:
    focus_duration: 5.0  # Seconds
    distraction_threshold: 0.7
    salience_sensitivity: 0.8

  # Language module settings
  language:
    vocabulary_growth_rate: 0.1
    grammar_complexity_scaling: true

  # Emotion module settings
  emotion:
    baseline_arousal: 0.3
    valence_range: [-1.0, 1.0]
    emotion_decay_rate: 0.1

  # Social module settings
  social:
    relationship_memory_capacity: 50
    theory_of_mind_enabled: true

# Interface settings
interfaces:
  # Mother LLM interface
  mother:
    enabled: true
    llm_url: "http://192.168.2.12:1234"
    model: "qwen2.5-7b-instruct"  # Default model
    personality: "nurturing"
    teaching_strategies:
      - "scaffolding"
      - "repetition"
      - "socratic"
    tts_enabled: true
    tts_voice: "af_bella"

  # Researcher interface
  researcher:
    enabled: true
    metrics_collection_interval: 60  # Seconds
    chart_update_interval: 5  # Seconds
    log_brain_states: true

# Neural substrate settings
neural_substrate:
  neuron_activation_threshold: 0.5
  hebbian_learning_rate: 0.01
  inhibitory_ratio: 0.2  # Ratio of inhibitory to excitatory neurons
  synapse_initial_strength: 0.1
  network_sparsity: 0.8  # Initial connection sparsity

# Storage settings
storage:
  vector_index_type: "Flat"  # Flat, IVF, HNSW
  vector_dimension: 768
  experience_log_retention: 10000  # Number of experiences to keep
  state_backup_count: 20  # Number of state backups to retain

# Homeostasis settings
homeostasis:
  energy_depletion_rate: 0.01
  energy_recovery_rate: 0.05
  arousal_regulation_strength: 0.3
  cognitive_load_threshold: 0.8
  coherence_target: 0.7

# Learning settings
learning:
  consolidation_schedule: "sleep"  # "continuous", "sleep", "periodic"
  pruning_threshold: 0.1
  reinforcement_learning_rate: 0.01
  meta_learning_enabled: true
