# LMM Configuration

# General settings
development_mode: true
log_level: "INFO"

# API endpoints
apis:
  llm_api_url: "http://192.168.2.12:1234"
  tts_api_url: "http://127.0.0.1:7860"

# Mother LLM settings
mother:
  voice: "af_bella"
  teaching_style: "socratic"
  personality:
    nurturing: 0.8
    patient: 0.9
    encouraging: 0.8
    structured: 0.7
    responsive: 0.9

# Development settings
development:
  default_rate: 0.01
  default_cycles: 100
  save_interval: 50
  critical_periods_enabled: true
  milestone_tracking_enabled: true
  accelerated_mode: false

# Neural substrate settings
neural_substrate:
  default_activation_function: "sigmoid"
  default_learning_rate: 0.01
  hebbian_learning_enabled: true
  use_gpu: true
  fallback_to_cpu: true
  batch_size: 64

# Visualization settings
visualization:
  enabled: true
  update_interval: 5
  show_neural_activity: true
  show_development_charts: true
  show_memory_visualization: true

# Storage settings
storage:
  checkpoint_dir: "storage/checkpoints"
  experience_dir: "storage/experiences"
  memory_dir: "storage/memories"
  backup_enabled: true
  backup_interval: 1000
  max_backups: 10

# Active cognitive modules
active_modules:
  - perception
  - attention
  - memory
  - language
  - emotion
  - consciousness
  - executive
  - social
  - motivation
  - temporal
  - creativity
  - self_regulation
  - learning
  - identity
  - belief 